'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ALBATROS-INFORMATICA")>  _
        Public Property NombreEmpresa() As String
            Get
                Return CType(Me("NombreEmpresa"),String)
            End Get
            Set
                Me("NombreEmpresa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property Versionwingest() As String
            Get
                Return CType(Me("Versionwingest"),String)
            End Get
            Set
                Me("Versionwingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServidorSQLServerWingest() As String
            Get
                Return CType(Me("ServidorSQLServerWingest"),String)
            End Get
            Set
                Me("ServidorSQLServerWingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserSQLServerWingest() As String
            Get
                Return CType(Me("UserSQLServerWingest"),String)
            End Get
            Set
                Me("UserSQLServerWingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PwdSQLServerWingest() As String
            Get
                Return CType(Me("PwdSQLServerWingest"),String)
            End Get
            Set
                Me("PwdSQLServerWingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1433")>  _
        Public Property PortSQLServerWingest() As String
            Get
                Return CType(Me("PortSQLServerWingest"),String)
            End Get
            Set
                Me("PortSQLServerWingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DIPLAN")>  _
        Public Property DataBaseSQLServerWingest() As String
            Get
                Return CType(Me("DataBaseSQLServerWingest"),String)
            End Get
            Set
                Me("DataBaseSQLServerWingest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FirstInit() As String
            Get
                Return CType(Me("FirstInit"),String)
            End Get
            Set
                Me("FirstInit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("yyyy-dd-MM")>  _
        Public Property FormatFecha_SqlServer() As String
            Get
                Return CType(Me("FormatFecha_SqlServer"),String)
            End Get
            Set
                Me("FormatFecha_SqlServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=JESPARTERO\JORGEESP;Initial Catalog=wgdemo;User ID=sa;Password=sql_se"& _ 
            "rver")>  _
        Public ReadOnly Property wgdemoConnectionString() As String
            Get
                Return CType(Me("wgdemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("#.##0,00")>  _
        Public Property FormatNumer_Importes_Excel() As String
            Get
                Return CType(Me("FormatNumer_Importes_Excel"),String)
            End Get
            Set
                Me("FormatNumer_Importes_Excel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("#.##0")>  _
        Public Property FormatNumer_Cantidades_Excel() As String
            Get
                Return CType(Me("FormatNumer_Cantidades_Excel"),String)
            End Get
            Set
                Me("FormatNumer_Cantidades_Excel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathEtiquetasLabelMatrix() As String
            Get
                Return CType(Me("PathEtiquetasLabelMatrix"),String)
            End Get
            Set
                Me("PathEtiquetasLabelMatrix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FicheroAccessEtiquetas() As String
            Get
                Return CType(Me("FicheroAccessEtiquetas"),String)
            End Get
            Set
                Me("FicheroAccessEtiquetas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Canal() As String
            Get
                Return CType(Me("Canal"),String)
            End Get
            Set
                Me("Canal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathEtiquetasLabelMatrixOriginal() As String
            Get
                Return CType(Me("PathEtiquetasLabelMatrixOriginal"),String)
            End Get
            Set
                Me("PathEtiquetasLabelMatrixOriginal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2018")>  _
        Public Property Ejercicio() As String
            Get
                Return CType(Me("Ejercicio"),String)
            End Get
            Set
                Me("Ejercicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathProgramaLabelMatrix() As String
            Get
                Return CType(Me("PathProgramaLabelMatrix"),String)
            End Get
            Set
                Me("PathProgramaLabelMatrix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property MostrarVentanaMSDos() As String
            Get
                Return CType(Me("MostrarVentanaMSDos"),String)
            End Get
            Set
                Me("MostrarVentanaMSDos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property TiempoEsperaEntreEtiquetas() As String
            Get
                Return CType(Me("TiempoEsperaEntreEtiquetas"),String)
            End Get
            Set
                Me("TiempoEsperaEntreEtiquetas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("48.")>  _
        Public Property CodArticulosLabelMatrix() As String
            Get
                Return CType(Me("CodArticulosLabelMatrix"),String)
            End Get
            Set
                Me("CodArticulosLabelMatrix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.44")>  _
        Public Property IPImpresora() As String
            Get
                Return CType(Me("IPImpresora"),String)
            End Get
            Set
                Me("IPImpresora") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WingestLabelMatrix.My.MySettings
            Get
                Return Global.WingestLabelMatrix.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
